/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import bean.HoaDon;
import bean.LoaiThucPham;
import bean.login_user;
import controller.ControllerHoaDon;
import controller.ControllerSanPham;
import controller.ControllerUser;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.RowFilter;
import javax.swing.table.AbstractTableModel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import model.ModelHoaDon;
import model.ModelLogin_user;
import renderer.ComboBoxModelLoaiThucPham;

/**
 *
 * @author Administrator
 */
public class pnGiaoDich extends javax.swing.JPanel {

    private ControllerSanPham controllerSanPham;
    private ControllerHoaDon controllerHD;
    private DefaultTableModel model;
    private ModelHoaDon modelHoaDon;
    private String tenKH = "";
    private String diachi = "";
    private double ttien;
    private double ptra;
    private double giamgia;
    private double giamgiaPT;
    private int crow = -1;
    private String nhanvien = "";
    private ControllerUser controller;
    private JTable table;
    private ModelLogin_user modelLogin_user;

    public pnGiaoDich() {
        initComponents();
        model = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        modelHoaDon = new ModelHoaDon();
        controllerSanPham = new ControllerSanPham(tbSanPham);
        controllerSanPham.loadTable();
        controllerHD = new ControllerHoaDon();

        controller = new ControllerUser(table);
//        controller.checkUsername(username);

        modelLogin_user = new ModelLogin_user();
        ArrayList<login_user> user = modelLogin_user.getUserLogin();
        login_user fullname = user.get(0);
        nhanvien = fullname.getFullname();

        loadTableHoaDon(null);
        loadLoaiThucPham(null);
        btThemGiam.setEnabled(false);
        btBot.setEnabled(false);
        btXoa.setEnabled(false);
        btInHoaDon.setEnabled(false);
        btLammoi.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jSplitPane1 = new javax.swing.JSplitPane();
        pnThem = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        tbSanPham = new javax.swing.JTable();
        jPanel17 = new javax.swing.JPanel();
        jLabel49 = new javax.swing.JLabel();
        tfTenFind = new javax.swing.JTextField();
        jLabel50 = new javax.swing.JLabel();
        cbLoaiFind = new javax.swing.JComboBox();
        jPanel20 = new javax.swing.JPanel();
        btMenuFind = new javax.swing.JButton();
        btNhapLai = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        btThemGiam = new javax.swing.JButton();
        btBot = new javax.swing.JButton();
        btXoa = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        tfTenSanPham = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        spSoluong = new javax.swing.JSpinner();
        jScrollPane4 = new javax.swing.JScrollPane();
        taTTT = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        tfTenKhachHang = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tfDiaChi = new javax.swing.JTextField();
        tfGia = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbHoaDon = new javax.swing.JTable();
        jPanel12 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        btTinhTien = new javax.swing.JButton();
        btInHoaDon = new javax.swing.JButton();
        btLammoi = new javax.swing.JButton();
        tfTongTien = new javax.swing.JTextField();
        tfGiamGia = new javax.swing.JTextField();
        tfPhaiTra = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tfGiamPT = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        jSplitPane1.setOneTouchExpandable(true);

        pnThem.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Thuốc điều trị", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(0, 0, 204))); // NOI18N
        pnThem.setPreferredSize(new java.awt.Dimension(600, 579));

        tbSanPham.setAutoCreateRowSorter(true);
        tbSanPham.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbSanPham.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tbSanPham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tbSanPhamMousePressed(evt);
            }
        });
        tbSanPham.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tbSanPhamKeyReleased(evt);
            }
        });
        jScrollPane7.setViewportView(tbSanPham);

        jLabel49.setText("Tên:");

        jLabel50.setText("Loại");

        cbLoaiFind.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel49)
                    .addComponent(jLabel50))
                .addGap(18, 18, 18)
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfTenFind)
                    .addComponent(cbLoaiFind, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(1, 1, 1))
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel49)
                    .addComponent(tfTenFind, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel50)
                    .addComponent(cbLoaiFind, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jPanel17Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {cbLoaiFind, tfTenFind});

        jPanel20.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        jPanel20.setLayout(new java.awt.GridLayout(2, 1, 0, 10));

        btMenuFind.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btMenuFind.setForeground(new java.awt.Color(0, 102, 0));
        btMenuFind.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search-red-icon.png"))); // NOI18N
        btMenuFind.setText("Tìm");
        btMenuFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMenuFindActionPerformed(evt);
            }
        });
        jPanel20.add(btMenuFind);

        btNhapLai.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btNhapLai.setForeground(new java.awt.Color(0, 102, 0));
        btNhapLai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Button-Refresh-icon_1.png"))); // NOI18N
        btNhapLai.setText("Reset");
        btNhapLai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNhapLaiActionPerformed(evt);
            }
        });
        jPanel20.add(btNhapLai);

        btThemGiam.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btThemGiam.setForeground(new java.awt.Color(0, 153, 0));
        btThemGiam.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Button-Add-icon.png"))); // NOI18N
        btThemGiam.setText("Thêm");
        btThemGiam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btThemGiamActionPerformed(evt);
            }
        });
        jPanel3.add(btThemGiam);

        btBot.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btBot.setForeground(new java.awt.Color(0, 153, 0));
        btBot.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/sub-icon.png"))); // NOI18N
        btBot.setText("Bớt");
        btBot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBotActionPerformed(evt);
            }
        });
        jPanel3.add(btBot);

        btXoa.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btXoa.setForeground(new java.awt.Color(0, 153, 0));
        btXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/button-del-icon.png"))); // NOI18N
        btXoa.setText("Xóa");
        btXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btXoaActionPerformed(evt);
            }
        });
        jPanel3.add(btXoa);

        jLabel2.setText("Tên sản phẩm :");

        tfTenSanPham.setEnabled(false);
        tfTenSanPham.setMinimumSize(new java.awt.Dimension(80, 30));
        tfTenSanPham.setPreferredSize(new java.awt.Dimension(40, 25));

        jLabel8.setText("Số lượng :");

        jLabel9.setText("Ghi chú :");

        spSoluong.setMinimumSize(new java.awt.Dimension(80, 30));
        spSoluong.setPreferredSize(new java.awt.Dimension(40, 25));

        taTTT.setColumns(20);
        taTTT.setRows(5);
        jScrollPane4.setViewportView(taTTT);

        jLabel1.setText("Tên khách hàng :");

        tfTenKhachHang.setMinimumSize(new java.awt.Dimension(80, 30));
        tfTenKhachHang.setPreferredSize(new java.awt.Dimension(80, 30));

        jLabel3.setText("Địa chỉ :");

        tfDiaChi.setMinimumSize(new java.awt.Dimension(80, 30));
        tfDiaChi.setPreferredSize(new java.awt.Dimension(40, 25));

        tfGia.setEnabled(false);
        tfGia.setMinimumSize(new java.awt.Dimension(80, 30));
        tfGia.setPreferredSize(new java.awt.Dimension(40, 25));

        jLabel4.setText("Giá :");

        javax.swing.GroupLayout pnThemLayout = new javax.swing.GroupLayout(pnThem);
        pnThem.setLayout(pnThemLayout);
        pnThemLayout.setHorizontalGroup(
            pnThemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnThemLayout.createSequentialGroup()
                .addGroup(pnThemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnThemLayout.createSequentialGroup()
                        .addComponent(jPanel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel20, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnThemLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnThemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnThemLayout.createSequentialGroup()
                                .addGroup(pnThemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel8))
                                .addGap(18, 18, 18)
                                .addGroup(pnThemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnThemLayout.createSequentialGroup()
                                        .addGroup(pnThemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(pnThemLayout.createSequentialGroup()
                                                .addComponent(tfTenSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(27, 27, 27)
                                                .addGroup(pnThemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel3)
                                                    .addComponent(jLabel4)))
                                            .addComponent(spSoluong, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(pnThemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(tfGia, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(tfDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jScrollPane4)))
                            .addGroup(pnThemLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tfTenKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
            .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        pnThemLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {spSoluong, tfDiaChi, tfGia, tfTenKhachHang, tfTenSanPham});

        pnThemLayout.setVerticalGroup(
            pnThemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnThemLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(pnThemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel20, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(pnThemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnThemLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(pnThemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(tfTenKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)))
                    .addGroup(pnThemLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(pnThemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfTenSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnThemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spSoluong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnThemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnThemLayout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(27, Short.MAX_VALUE))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)))
        );

        pnThemLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel2, jLabel8, spSoluong, tfDiaChi, tfGia, tfTenKhachHang, tfTenSanPham});

        jSplitPane1.setLeftComponent(pnThem);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Hóa đơn", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(0, 51, 204))); // NOI18N

        tbHoaDon.setAutoCreateRowSorter(true);
        tbHoaDon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbHoaDon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tbHoaDonMousePressed(evt);
            }
        });
        tbHoaDon.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tbHoaDonKeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(tbHoaDon);

        jPanel12.setLayout(new java.awt.GridBagLayout());

        jLabel10.setText("Tổng tiền :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipady = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(53, 71, 0, 0);
        jPanel12.add(jLabel10, gridBagConstraints);

        jLabel11.setText("Giảm giá :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipady = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(33, 68, 0, 0);
        jPanel12.add(jLabel11, gridBagConstraints);

        jLabel12.setText("Phải trả :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipady = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(28, 68, 0, 0);
        jPanel12.add(jLabel12, gridBagConstraints);

        btTinhTien.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btTinhTien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Pay-icon.png"))); // NOI18N
        btTinhTien.setText("Tính tiền");
        btTinhTien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTinhTienActionPerformed(evt);
            }
        });
        jPanel13.add(btTinhTien);

        btInHoaDon.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btInHoaDon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Printer-icon.png"))); // NOI18N
        btInHoaDon.setText("In hóa đơn");
        btInHoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btInHoaDonActionPerformed(evt);
            }
        });
        jPanel13.add(btInHoaDon);

        btLammoi.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btLammoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Button-Refresh-icon.png"))); // NOI18N
        btLammoi.setText("Làm mới");
        btLammoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLammoiActionPerformed(evt);
            }
        });
        jPanel13.add(btLammoi);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = 10;
        gridBagConstraints.ipadx = 449;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 11, 29, 0);
        jPanel12.add(jPanel13, gridBagConstraints);

        tfTongTien.setEnabled(false);
        tfTongTien.setPreferredSize(new java.awt.Dimension(50, 25));
        tfTongTien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfTongTienActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.ipadx = 129;
        gridBagConstraints.ipady = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(47, 18, 0, 0);
        jPanel12.add(tfTongTien, gridBagConstraints);

        tfGiamGia.setText("0");
        tfGiamGia.setPreferredSize(new java.awt.Dimension(50, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridheight = 4;
        gridBagConstraints.ipadx = 129;
        gridBagConstraints.ipady = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(27, 18, 0, 0);
        jPanel12.add(tfGiamGia, gridBagConstraints);

        tfPhaiTra.setEditable(false);
        tfPhaiTra.setForeground(new java.awt.Color(255, 0, 51));
        tfPhaiTra.setPreferredSize(new java.awt.Dimension(50, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.ipadx = 129;
        gridBagConstraints.ipady = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(22, 18, 0, 0);
        jPanel12.add(tfPhaiTra, gridBagConstraints);

        jLabel5.setText("Giảm % :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.ipady = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(35, 36, 0, 0);
        jPanel12.add(jLabel5, gridBagConstraints);

        tfGiamPT.setText("0");
        tfGiamPT.setMinimumSize(new java.awt.Dimension(70, 25));
        tfGiamPT.setPreferredSize(new java.awt.Dimension(79, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridheight = 4;
        gridBagConstraints.ipadx = 32;
        gridBagConstraints.ipady = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(27, 4, 0, 0);
        jPanel12.add(tfGiamPT, gridBagConstraints);

        jLabel6.setText("%");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridheight = 4;
        gridBagConstraints.ipadx = 15;
        gridBagConstraints.ipady = 14;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(26, 19, 0, 0);
        jPanel12.add(jLabel6, gridBagConstraints);

        jLabel7.setText("VNĐ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(56, 18, 0, 0);
        jPanel12.add(jLabel7, gridBagConstraints);

        jLabel13.setText("VNĐ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(33, 18, 0, 0);
        jPanel12.add(jLabel13, gridBagConstraints);

        jLabel14.setText("VNĐ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(28, 18, 0, 0);
        jPanel12.add(jLabel14, gridBagConstraints);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, 265, Short.MAX_VALUE))
        );

        jSplitPane1.setRightComponent(jPanel2);

        add(jSplitPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void tbSanPhamMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbSanPhamMousePressed
        setForm();
        btThemGiam.setEnabled(true);
        btXoa.setEnabled(true);
        btBot.setEnabled(true);
    }//GEN-LAST:event_tbSanPhamMousePressed

    private void tbSanPhamKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbSanPhamKeyReleased
        setForm();
        btThemGiam.setEnabled(true);
        btXoa.setEnabled(true);
        btBot.setEnabled(true);
    }//GEN-LAST:event_tbSanPhamKeyReleased

    private void btMenuFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMenuFindActionPerformed
        String name = tfTenFind.getText();

        //kiếm theo id_news, tên
        TableRowSorter sorter = new TableRowSorter(tbSanPham.getModel());
        tbSanPham.setRowSorter(sorter);
        RowFilter<AbstractTableModel, Object> filterUserName = RowFilter.regexFilter("(?i)" + name, 1);
        ArrayList<RowFilter<AbstractTableModel, Object>> alFilter = new ArrayList<>();
        alFilter.add(filterUserName);

        //kiếm theo combobox
        String id_find_chooser = (String.valueOf(cbLoaiFind.getSelectedItem()));
        if (cbLoaiFind.getSelectedIndex() != 0) {
            RowFilter<AbstractTableModel, Object> filterLoai = RowFilter.regexFilter(id_find_chooser, 2);
            alFilter.add(filterLoai);
        }
        RowFilter<AbstractTableModel, Object> filterAnd = RowFilter.andFilter(alFilter);
        sorter.setRowFilter(filterAnd);
    }//GEN-LAST:event_btMenuFindActionPerformed

    private void btNhapLaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNhapLaiActionPerformed
        resetFrom();
    }//GEN-LAST:event_btNhapLaiActionPerformed

    private void btThemGiamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btThemGiamActionPerformed
        crow = tbSanPham.getSelectedRow();
        btInHoaDon.setEnabled(false);
        btTinhTien.setEnabled(true);
        int crow1 = -1;
        crow1 = tbHoaDon.getSelectedRow();
        HoaDon hoadon = null;
        int soluong = (int) spSoluong.getValue();
        if (crow < 0 && crow1 < 0) {
            JOptionPane.showMessageDialog(null, "Chọn món cần thêm");
            return;
        }
        if (soluong <= 0) {
            JOptionPane.showMessageDialog(null, "Nhập vào số lớn hơn 0");
            return;
        } else {
            int thanhtien = 0;
            String tenKH = tfTenKhachHang.getText();
            String diachi = tfDiaChi.getText();
            thanhtien = Integer.parseInt(tfGia.getText()) * soluong;
            int gia = Integer.parseInt(tfGia.getText());
            String tenSP = tfTenSanPham.getText();
            String ghichu = taTTT.getText();
            Date date = new Date();
            Date date1 = new java.sql.Date(date.getTime());
            hoadon = new HoaDon(0, tenKH, diachi, tenSP, soluong, gia, thanhtien, ghichu, (java.sql.Date) date1, nhanvien);
        }
        if (controllerHD.add(hoadon) > 0) {
            loadTableHoaDon(hoadon);
            thanhtoan();
        }
    }//GEN-LAST:event_btThemGiamActionPerformed

    private void btXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btXoaActionPerformed
        crow = tbHoaDon.getSelectedRow();
        btInHoaDon.setEnabled(false);
        int idHD = 0;
        HoaDon hoadon = null;
        if (crow < 0) {
            JOptionPane.showMessageDialog(null, "Vui lòng chọn một dòng để xóa!");
        } else {
            idHD = Integer.parseInt(tbHoaDon.getValueAt(crow, 0).toString());
            hoadon = new HoaDon(idHD, "", "", "", 0, 0, 0, "", null, "");
            int p = JOptionPane.showConfirmDialog(null, "Bạn có chắc chắn muốn xóa", "Xóa?", JOptionPane.YES_NO_OPTION);
            if (p == 0) {
                controllerHD.del(hoadon);
                loadTableHoaDon(hoadon);
                thanhtoan();
            }
        }
    }//GEN-LAST:event_btXoaActionPerformed

    private void tbHoaDonKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbHoaDonKeyReleased
        setFormHD();
    }//GEN-LAST:event_tbHoaDonKeyReleased

    private void tbHoaDonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbHoaDonMousePressed
        setFormHD();
    }//GEN-LAST:event_tbHoaDonMousePressed

    private void btTinhTienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTinhTienActionPerformed
        int tongtien = 0;
        double phaitra = 0;
        ArrayList<HoaDon> thanhtoan = modelHoaDon.getList();
        if (tfGiamGia.getText().equals("")) {
            tfGiamGia.setText("0");
        }
        if (tfGiamPT.getText().equals("")) {
            tfGiamPT.setText("0");
        }
        double giamgiaTM = Double.parseDouble(tfGiamGia.getText());
        double giamPhanTram = Double.parseDouble(tfGiamPT.getText());
        for (int i = 0; i < thanhtoan.size(); i++) {
            tongtien += thanhtoan.get(i).getSoluong() * (thanhtoan.get(i).getGia());
        }
        double GiamPT = (float) giamPhanTram * tongtien / 100;
        phaitra = (double) tongtien - giamgiaTM - GiamPT;
        if (phaitra < 0) {
            tfPhaiTra.setText(String.valueOf(phaitra));
            JOptionPane.showMessageDialog(null, "Giảm giá hơi sai sai :((?");
        } else {
            tfPhaiTra.setText(String.valueOf(phaitra));
        }
//        tongtien = tongtien;
        tfTongTien.setText(String.valueOf(tongtien));
        btInHoaDon.setEnabled(true);
        ttien = Double.parseDouble(tfTongTien.getText());
        ptra = Double.parseDouble(tfPhaiTra.getText());
        giamgia = Double.parseDouble(tfGiamGia.getText());
        giamgiaPT = Double.parseDouble(tfGiamPT.getText());
        tenKH = tfTenKhachHang.getText();
        diachi = tfDiaChi.getText();
    }//GEN-LAST:event_btTinhTienActionPerformed
    private void btInHoaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btInHoaDonActionPerformed
        new FrInPhieu(tenKH, diachi, ttien, giamgia, giamgiaPT, ptra, nhanvien).setVisible(true);
        btLammoi.setEnabled(true);
        btInHoaDon.setEnabled(false);
    }//GEN-LAST:event_btInHoaDonActionPerformed

    private void btBotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBotActionPerformed
        crow = tbSanPham.getSelectedRow();
        btInHoaDon.setEnabled(false);
        int crow1 = -1;
        crow1 = tbHoaDon.getSelectedRow();
        HoaDon hoadon = null;
        int soluong = (int) spSoluong.getValue();
        if (crow < 0 && crow1 < 0) {
            JOptionPane.showMessageDialog(null, "Chọn món cần giảm");
            return;
        }
        if (soluong <= 0) {
            JOptionPane.showMessageDialog(null, "Nhập vào số lớn hơn 0");
            return;
        }
        else {
            int thanhtien = 0;
            String tenKH = tfTenKhachHang.getText();
            String diachi = tfDiaChi.getText();
            thanhtien = Integer.parseInt(tfGia.getText()) * soluong;
            int gia = Integer.parseInt(tfGia.getText());
            String tenSP = tfTenSanPham.getText();
            String ghichu = taTTT.getText();
            Date date = new Date();
            Date date1 = new java.sql.Date(date.getTime());
            hoadon = new HoaDon(0, tenKH, diachi, tenSP, soluong, gia, thanhtien, ghichu, (java.sql.Date) date1, nhanvien);
        }
        if (controllerHD.sub(hoadon) > 0) {
            loadTableHoaDon(hoadon);
            thanhtoan();
        }
    }//GEN-LAST:event_btBotActionPerformed

    private void btLammoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLammoiActionPerformed
        controllerHD.in();
        loadTableHoaDon(null);
        btLammoi.setEnabled(false);
        btTinhTien.setEnabled(false);

    }//GEN-LAST:event_btLammoiActionPerformed

    private void tfTongTienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfTongTienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfTongTienActionPerformed
    public void loadTableHoaDon(HoaDon item) {
        controllerHD.loadTable(tbHoaDon, model, item);
    }

    public void loadLoaiThucPham(LoaiThucPham item) {
        cbLoaiFind.setModel(new ComboBoxModelLoaiThucPham(item, true));
    }

    public void setForm() {
        crow = tbSanPham.getSelectedRow();
        String name = tbSanPham.getValueAt(crow, 1).toString();
        String gia = tbSanPham.getValueAt(crow, 7).toString();
        tfTenSanPham.setText(name);
        tfGia.setText(gia);
        btThemGiam.setEnabled(true);
        btXoa.setEnabled(true);
        btBot.setEnabled(true);
    }

    public void setFormHD() {
        crow = tbHoaDon.getSelectedRow();
        String tenKh = tbHoaDon.getValueAt(crow, 1).toString();
        String diachi = tbHoaDon.getValueAt(crow, 2).toString();
        String name1 = tbHoaDon.getValueAt(crow, 3).toString();
        String gia1 = tbHoaDon.getValueAt(crow, 5).toString();
        tfTenSanPham.setText(name1);
        tfGia.setText(gia1);
        tfTenKhachHang.setText(tenKh);
        tfDiaChi.setText(diachi);
        btThemGiam.setEnabled(true);
        btXoa.setEnabled(true);
        btBot.setEnabled(true);
    }

    public void thanhtoan() {
        HoaDon item = null;
        int tongtien = 0;
        double phaitra = 0;
        item = new HoaDon(0, "", 0, 0, tongtien, "", true);
        ArrayList<HoaDon> thanhtoan = modelHoaDon.getList();
        int giamgiaTM = Integer.parseInt(tfGiamGia.getText());
        int giamPhanTram = Integer.parseInt(tfGiamPT.getText());
        for (int i = 0; i < thanhtoan.size(); i++) {
            tongtien += thanhtoan.get(i).getSoluong() * (thanhtoan.get(i).getGia());
        }
        double GiamPT = (float) giamPhanTram * tongtien / 100;
        phaitra = tongtien - giamgiaTM - GiamPT;
        if (phaitra < 0) {
            tfPhaiTra.setText("Lỗ : " + String.valueOf(phaitra) + " VNĐ ");

        } else {
            tfPhaiTra.setText(String.valueOf(phaitra) + " VNĐ");
        }
        tfTongTien.setText(String.valueOf(tongtien) + " VNĐ ");

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btBot;
    private javax.swing.JButton btInHoaDon;
    private javax.swing.JButton btLammoi;
    private javax.swing.JButton btMenuFind;
    private javax.swing.JButton btNhapLai;
    private javax.swing.JButton btThemGiam;
    private javax.swing.JButton btTinhTien;
    private javax.swing.JButton btXoa;
    private javax.swing.JComboBox cbLoaiFind;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JPanel pnThem;
    private javax.swing.JSpinner spSoluong;
    private javax.swing.JTextArea taTTT;
    private javax.swing.JTable tbHoaDon;
    private javax.swing.JTable tbSanPham;
    private javax.swing.JTextField tfDiaChi;
    private javax.swing.JTextField tfGia;
    private javax.swing.JTextField tfGiamGia;
    private javax.swing.JTextField tfGiamPT;
    private javax.swing.JTextField tfPhaiTra;
    private javax.swing.JTextField tfTenFind;
    private javax.swing.JTextField tfTenKhachHang;
    private javax.swing.JTextField tfTenSanPham;
    private javax.swing.JTextField tfTongTien;
    // End of variables declaration//GEN-END:variables

    private void resetFrom() {
        tfTenFind.setText("");
        cbLoaiFind.setSelectedIndex(0);
    }
}
