/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import bean.LoaiThucPham;
import controller.ControllerLoaiThucPham;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.AbstractTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Administrator
 */
public class pnLoaiThucPham extends javax.swing.JPanel {

    private ControllerLoaiThucPham controller;
    private int row = -1;

    public pnLoaiThucPham() {
        initComponents();
        controller = new ControllerLoaiThucPham(tbLoaiThucPham);
        controller.loadTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        pnUserRight = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbLoaiThucPham = new javax.swing.JTable();
        pnUserLeft = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tfIdThucPham = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tfLoaiThucPham = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        btThem = new javax.swing.JButton();
        btSua = new javax.swing.JButton();
        btNhapLai = new javax.swing.JButton();
        btXoa = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        tfIdThucPhamFind = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tfLoaiThucPhamFind = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        btSearch = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        jSplitPane1.setOneTouchExpandable(true);

        pnUserRight.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Danh sách", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(0, 102, 0))); // NOI18N

        tbLoaiThucPham.setAutoCreateRowSorter(true);
        tbLoaiThucPham.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbLoaiThucPham.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tbLoaiThucPham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tbLoaiThucPhamMousePressed(evt);
            }
        });
        tbLoaiThucPham.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tbLoaiThucPhamKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tbLoaiThucPham);

        javax.swing.GroupLayout pnUserRightLayout = new javax.swing.GroupLayout(pnUserRight);
        pnUserRight.setLayout(pnUserRightLayout);
        pnUserRightLayout.setHorizontalGroup(
            pnUserRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnUserRightLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 425, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnUserRightLayout.setVerticalGroup(
            pnUserRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnUserRightLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 484, Short.MAX_VALUE)
                .addContainerGap())
        );

        jSplitPane1.setRightComponent(pnUserRight);

        pnUserLeft.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "From chức năng", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(0, 102, 0)), javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5))); // NOI18N
        pnUserLeft.setPreferredSize(new java.awt.Dimension(445, 500));
        pnUserLeft.setLayout(new java.awt.BorderLayout());

        jLabel1.setText("ID thực phẩm:");

        tfIdThucPham.setEnabled(false);
        tfIdThucPham.setPreferredSize(new java.awt.Dimension(6, 32));

        jLabel2.setText("Loại thực phẩm:");

        tfLoaiThucPham.setPreferredSize(new java.awt.Dimension(6, 32));
        tfLoaiThucPham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfLoaiThucPhamActionPerformed(evt);
            }
        });

        btThem.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Button-Add-icon.png"))); // NOI18N
        btThem.setText("Thêm");
        btThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btThemActionPerformed(evt);
            }
        });
        jPanel3.add(btThem);

        btSua.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/edit-icon.png"))); // NOI18N
        btSua.setText("Sửa");
        btSua.setPreferredSize(new java.awt.Dimension(85, 25));
        btSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSuaActionPerformed(evt);
            }
        });
        jPanel3.add(btSua);

        btNhapLai.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btNhapLai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Button-Refresh-icon_1.png"))); // NOI18N
        btNhapLai.setText("Nhập lại");
        btNhapLai.setPreferredSize(new java.awt.Dimension(95, 25));
        btNhapLai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNhapLaiActionPerformed(evt);
            }
        });
        jPanel3.add(btNhapLai);

        btXoa.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/button-del-icon.png"))); // NOI18N
        btXoa.setText("Xóa");
        btXoa.setPreferredSize(new java.awt.Dimension(85, 25));
        btXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btXoaActionPerformed(evt);
            }
        });
        jPanel3.add(btXoa);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tfIdThucPham, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                    .addComponent(tfLoaiThucPham, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addComponent(tfIdThucPham, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfLoaiThucPham, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(27, 27, 27)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {tfIdThucPham, tfLoaiThucPham});

        pnUserLeft.add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Tìm kiếm", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(0, 102, 0))); // NOI18N

        jLabel3.setText("ID:");

        tfIdThucPhamFind.setPreferredSize(new java.awt.Dimension(6, 32));

        jLabel4.setText("Loại:");

        tfLoaiThucPhamFind.setPreferredSize(new java.awt.Dimension(6, 26));

        btSearch.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search-red-icon.png"))); // NOI18N
        btSearch.setText("Tìm kiếm");
        btSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSearchActionPerformed(evt);
            }
        });
        jPanel5.add(btSearch);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfLoaiThucPhamFind, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tfIdThucPhamFind, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfIdThucPhamFind, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tfLoaiThucPhamFind, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel4Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {tfIdThucPhamFind, tfLoaiThucPhamFind});

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pnUserLeft.add(jPanel2, java.awt.BorderLayout.SOUTH);

        jSplitPane1.setLeftComponent(pnUserLeft);

        add(jSplitPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void tbLoaiThucPhamMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbLoaiThucPhamMousePressed
        setForm();
    }//GEN-LAST:event_tbLoaiThucPhamMousePressed

    private void tbLoaiThucPhamKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbLoaiThucPhamKeyReleased
        setForm();
    }//GEN-LAST:event_tbLoaiThucPhamKeyReleased

    private void btThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btThemActionPerformed
        int id = 0;
        String name = tfLoaiThucPham.getText();
        LoaiThucPham obj = new LoaiThucPham(id, name);
        if (isValid("add", obj)) {
            if (controller.addItem(obj) > 0) {
                resetForm();
                JOptionPane.showMessageDialog(null, "Thêm thành công");
            } else {
                JOptionPane.showMessageDialog(null, "Có lỗi khi thêm");
            }
        }
    }//GEN-LAST:event_btThemActionPerformed

    private void btSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSuaActionPerformed
        int id = 0;
        row = tbLoaiThucPham.getSelectedRow();
        if (!tfIdThucPham.getText().isEmpty()) {
            id = Integer.parseInt(tfIdThucPham.getText());
        }
        String name = tfLoaiThucPham.getText();
        LoaiThucPham obj = new LoaiThucPham(id, name);
        if (isValid("edit", obj)) {
            int p = JOptionPane.showConfirmDialog(null, "Bạn có chắc chắn muốn sửa", "Sửa?", JOptionPane.YES_NO_OPTION);
            if (p == 0) {
                controller.edit(row, obj);
                JOptionPane.showMessageDialog(this, "Sủa thàng công!");
                resetForm();
            }
        }
    }//GEN-LAST:event_btSuaActionPerformed

    private void btNhapLaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNhapLaiActionPerformed
        resetForm();
    }//GEN-LAST:event_btNhapLaiActionPerformed

    private void btXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btXoaActionPerformed
        row = tbLoaiThucPham.getSelectedRow();
        int id = 0;
        if (!tfIdThucPham.getText().isEmpty()) {
            id = Integer.parseInt(tfIdThucPham.getText());
        }
        LoaiThucPham obj = new LoaiThucPham(id, "");
        if (isValid("del", obj)) {
            int p = JOptionPane.showConfirmDialog(null, "Bạn có chắc chắn muốn xóa", "Xóa?", JOptionPane.YES_NO_OPTION);
            if (p == 0) {
                controller.delItem(row, obj);
                JOptionPane.showMessageDialog(this, "Xóa thàng công!");
                resetForm();
            } else {
                JOptionPane.showMessageDialog(null, "Có lỗi trong quá trình xóa");
            }
        }
    }//GEN-LAST:event_btXoaActionPerformed

    private void btSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSearchActionPerformed
        TableRowSorter sorter = new TableRowSorter(tbLoaiThucPham.getModel());
        tbLoaiThucPham.setRowSorter(sorter);

        String id_cat = tfIdThucPhamFind.getText();
        String name = tfLoaiThucPhamFind.getText();

        RowFilter<AbstractTableModel, Object> fillterID = RowFilter.regexFilter(id_cat, 0);
        RowFilter<AbstractTableModel, Object> fillterName = RowFilter.regexFilter("(?i)" + name, 1);

        ArrayList<RowFilter<AbstractTableModel, Object>> alFillter = new ArrayList<>();
        alFillter.add(fillterID);
        alFillter.add(fillterName);

        RowFilter<AbstractTableModel, Object> fillterAnd = RowFilter.andFilter(alFillter);
        sorter.setRowFilter(fillterAnd);
    }//GEN-LAST:event_btSearchActionPerformed

    private void tfLoaiThucPhamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfLoaiThucPhamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfLoaiThucPhamActionPerformed
    private boolean isValid(String func, LoaiThucPham obj) {
        boolean result = true;
        switch (func) {
            case "add":
                if (obj.getLoai_thucpham().isEmpty()) {
                    JOptionPane.showMessageDialog(null, "Vui lòng nhập loại thực phẩm");
                    result = false;
                }
                break;
            case "del":
                if (obj.getId_loai()<= 0) {
                    JOptionPane.showMessageDialog(null, "Vui lòng chọn một dòng để xóa!");
                    result = false;
                }
                break;
            case "edit":
                if (obj.getLoai_thucpham().isEmpty()) {
                    JOptionPane.showMessageDialog(null, "Vui lòng nhập loại thực phẩm");
                    result = false;
                }
                if (obj.getId_loai()<= 0) {
                    JOptionPane.showMessageDialog(null, "Vui lòng chọn một dòng để sửa!");
                    result = false;
                }
                break;
        }
        return result;
    }

    public void setForm() {
        row = tbLoaiThucPham.getSelectedRow();
        String id = tbLoaiThucPham.getValueAt(row, 0).toString();
        String name = tbLoaiThucPham.getValueAt(row, 1).toString();

        tfIdThucPham.setText(id);
        tfLoaiThucPham.setText(name);
    }

    public void resetForm() {
        row = -1;
        tfIdThucPham.setText("");
        tfLoaiThucPham.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btNhapLai;
    private javax.swing.JButton btSearch;
    private javax.swing.JButton btSua;
    private javax.swing.JButton btThem;
    private javax.swing.JButton btXoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JPanel pnUserLeft;
    private javax.swing.JPanel pnUserRight;
    private javax.swing.JTable tbLoaiThucPham;
    private javax.swing.JTextField tfIdThucPham;
    private javax.swing.JTextField tfIdThucPhamFind;
    private javax.swing.JTextField tfLoaiThucPham;
    private javax.swing.JTextField tfLoaiThucPhamFind;
    // End of variables declaration//GEN-END:variables
}
