/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import bean.LoaiThucPham;
import bean.SanPham;
import controller.ControllerSanPham;
import java.sql.Timestamp;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.AbstractTableModel;
import javax.swing.table.TableRowSorter;
import renderer.ComboBoxModelLoaiThucPham;

/**
 *
 * @author Administrator
 */
public class pnQuanLiSanPham extends javax.swing.JPanel {

    private ControllerSanPham controller;
    private int row = -1;

    public pnQuanLiSanPham() {
        initComponents();
        controller = new ControllerSanPham(tbSanPham);
        controller.loadTable();
        loadLoai(null,false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        pnUserRight = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbSanPham = new javax.swing.JTable();
        pnUserLeft = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        tfID = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        btThem = new javax.swing.JButton();
        btSua = new javax.swing.JButton();
        btXoa = new javax.swing.JButton();
        btNhapLai = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        tfSolo = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tfDonVi = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        tfSoluong = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        tfGiaBan = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        spHanDung = new javax.swing.JSpinner();
        jLabel12 = new javax.swing.JLabel();
        cbLoai = new javax.swing.JComboBox();
        tfName = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        tfFind = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        btTimKiem = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        jSplitPane1.setOneTouchExpandable(true);

        pnUserRight.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Danh sách", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(0, 102, 0))); // NOI18N

        tbSanPham.setAutoCreateRowSorter(true);
        tbSanPham.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbSanPham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbSanPhamMouseClicked(evt);
            }
        });
        tbSanPham.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tbSanPhamKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tbSanPhamKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tbSanPham);

        javax.swing.GroupLayout pnUserRightLayout = new javax.swing.GroupLayout(pnUserRight);
        pnUserRight.setLayout(pnUserRightLayout);
        pnUserRightLayout.setHorizontalGroup(
            pnUserRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 517, Short.MAX_VALUE)
        );
        pnUserRightLayout.setVerticalGroup(
            pnUserRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 506, Short.MAX_VALUE)
        );

        jSplitPane1.setRightComponent(pnUserRight);

        pnUserLeft.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "From chức năng", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(0, 102, 0)), javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5))); // NOI18N
        pnUserLeft.setPreferredSize(new java.awt.Dimension(300, 350));
        pnUserLeft.setLayout(new java.awt.BorderLayout());

        jLabel2.setText("ID :");

        tfID.setEditable(false);
        tfID.setEnabled(false);
        tfID.setPreferredSize(new java.awt.Dimension(6, 32));
        tfID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfIDActionPerformed(evt);
            }
        });

        btThem.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Button-Add-icon.png"))); // NOI18N
        btThem.setText("Thêm");
        btThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btThemActionPerformed(evt);
            }
        });
        jPanel3.add(btThem);

        btSua.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/edit-icon.png"))); // NOI18N
        btSua.setText("Sửa");
        btSua.setPreferredSize(new java.awt.Dimension(85, 25));
        btSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSuaActionPerformed(evt);
            }
        });
        jPanel3.add(btSua);

        btXoa.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/button-del-icon.png"))); // NOI18N
        btXoa.setText("Xóa");
        btXoa.setPreferredSize(new java.awt.Dimension(85, 25));
        btXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btXoaActionPerformed(evt);
            }
        });
        jPanel3.add(btXoa);

        btNhapLai.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btNhapLai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Button-Refresh-icon_1.png"))); // NOI18N
        btNhapLai.setText("Nhập lại");
        btNhapLai.setPreferredSize(new java.awt.Dimension(100, 25));
        btNhapLai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNhapLaiActionPerformed(evt);
            }
        });
        jPanel3.add(btNhapLai);

        jLabel5.setText("Số lô :");

        tfSolo.setPreferredSize(new java.awt.Dimension(6, 32));
        tfSolo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfSoloActionPerformed(evt);
            }
        });

        jLabel6.setText("Hạn dùng :");

        jLabel8.setText("Loại");

        tfDonVi.setPreferredSize(new java.awt.Dimension(6, 32));
        tfDonVi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfDonViActionPerformed(evt);
            }
        });

        jLabel9.setText("Đơn vị :");

        tfSoluong.setPreferredSize(new java.awt.Dimension(6, 32));
        tfSoluong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfSoluongActionPerformed(evt);
            }
        });

        jLabel10.setText("Số lượng :");

        tfGiaBan.setPreferredSize(new java.awt.Dimension(6, 32));
        tfGiaBan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfGiaBanActionPerformed(evt);
            }
        });

        jLabel11.setText("Giá bán :");

        spHanDung.setModel(new javax.swing.SpinnerDateModel());
        spHanDung.setEditor(new javax.swing.JSpinner.DateEditor(spHanDung, "dd/MM/yyyy"));

        jLabel12.setText("Tên");

        cbLoai.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbLoai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbLoaiActionPerformed(evt);
            }
        });

        tfName.setPreferredSize(new java.awt.Dimension(6, 32));
        tfName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfSoluong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tfGiaBan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(spHanDung, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfDonVi, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                            .addComponent(tfSolo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(2, 2, 2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbLoai, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tfName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfID, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(tfName, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbLoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfDonVi, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfSolo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spHanDung, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfSoluong, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfGiaBan, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel10, jLabel2, jLabel5, jLabel6, jLabel8, jLabel9});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {cbLoai, spHanDung, tfDonVi, tfGiaBan, tfID, tfSolo, tfSoluong});

        pnUserLeft.add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Tìm kiếm", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(0, 0, 153))); // NOI18N

        jLabel3.setText("Nhập vào :");

        tfFind.setPreferredSize(new java.awt.Dimension(6, 32));

        btTimKiem.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btTimKiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search-red-icon.png"))); // NOI18N
        btTimKiem.setText("Tìm kiếm");
        btTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTimKiemActionPerformed(evt);
            }
        });
        jPanel5.add(btTimKiem);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfFind, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfFind, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnUserLeft.add(jPanel2, java.awt.BorderLayout.SOUTH);

        jSplitPane1.setLeftComponent(pnUserLeft);

        add(jSplitPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void tfIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfIDActionPerformed

    private void btThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btThemActionPerformed
        int id = 0;
        String name = tfName.getText();
        String donvi = tfDonVi.getText();
        String solo = tfSolo.getText();
        Date date = (Date) spHanDung.getValue();
        Timestamp hangdung = new Timestamp(date.getTime());
        String soluong = tfSoluong.getText();
        String dongia = tfGiaBan.getText();
        LoaiThucPham loai = (LoaiThucPham) cbLoai.getSelectedItem();
        SanPham obj = new SanPham(id, name, donvi, solo, hangdung, soluong, dongia,loai.getId_loai(),loai);
        if (isValid("add", obj)) {
            if (controller.addItem(obj) > 0) {
                resetForm();
                JOptionPane.showMessageDialog(null, "Thêm thành công");
            } else {
                JOptionPane.showMessageDialog(null, "Có lỗi khi thêm");
            }
        }
    }//GEN-LAST:event_btThemActionPerformed

    private void btSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSuaActionPerformed
        int id = 0;
        row = tbSanPham.getSelectedRow();
        if (!tfID.getText().isEmpty()) {
            id = Integer.parseInt(tfID.getText());
        }
        String name = tfName.getText();
        String donvi = tfDonVi.getText();
        String solo = tfSolo.getText();
        Date date = (Date) spHanDung.getValue();
        Timestamp hangdung = new Timestamp(date.getTime());
        String soluong = tfSoluong.getText();
        String dongia = tfGiaBan.getText();
        LoaiThucPham loai = (LoaiThucPham) cbLoai.getSelectedItem();
        SanPham obj = new SanPham(id, name, donvi, solo, hangdung, soluong, dongia,loai.getId_loai(),loai);
        if (isValid("edit", obj)) {
            int p = JOptionPane.showConfirmDialog(null, "Bạn có chắc chắn muốn sửa", "Sửa?", JOptionPane.YES_NO_OPTION);
            if (p == 0) {
                controller.edit(row, obj);
                JOptionPane.showMessageDialog(this, "Sửa thàng công!");
                resetForm();
            }
        }
    }//GEN-LAST:event_btSuaActionPerformed

    private void btNhapLaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNhapLaiActionPerformed
        resetForm();
    }//GEN-LAST:event_btNhapLaiActionPerformed

    private void btXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btXoaActionPerformed
        row = tbSanPham.getSelectedRow();
        int id = 0;
        if (!tfID.getText().isEmpty()) {
            id = Integer.parseInt(tfID.getText());
        }
        SanPham obj = new SanPham(id, "", "", "", null, "", "",0,null);
        if (isValid("del", obj)) {
            int p = JOptionPane.showConfirmDialog(null, "Bạn có chắc chắn muốn xóa", "Xóa?", JOptionPane.YES_NO_OPTION);
            if (p == 0) {
                controller.delItem(row, obj);
                JOptionPane.showMessageDialog(this, "Xóa thàng công!");
                resetForm();
            }
        }
    }//GEN-LAST:event_btXoaActionPerformed

    private void tfSoloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfSoloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfSoloActionPerformed

    private void tfDonViActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfDonViActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfDonViActionPerformed

    private void tfSoluongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfSoluongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfSoluongActionPerformed

    private void tfGiaBanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfGiaBanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfGiaBanActionPerformed

    private void btTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTimKiemActionPerformed
        String name = tfFind.getText();

        //kiếm theo id,tên...
        TableRowSorter sorter = new TableRowSorter(tbSanPham.getModel());
        tbSanPham.setRowSorter(sorter);
        RowFilter<AbstractTableModel, Object> filterName = RowFilter.regexFilter("(?i)" + name,0,1,2,3,4,6,7);
        ArrayList<RowFilter<AbstractTableModel, Object>> alFilter = new ArrayList<>();
        alFilter.add(filterName);
        
        RowFilter<AbstractTableModel, Object> filterAnd = RowFilter.orFilter(alFilter);
        sorter.setRowFilter(filterAnd);
    }//GEN-LAST:event_btTimKiemActionPerformed

    private void tfNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNameActionPerformed

    private void tbSanPhamKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbSanPhamKeyReleased
        setForm();
    }//GEN-LAST:event_tbSanPhamKeyReleased

    private void tbSanPhamKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbSanPhamKeyPressed
        setForm();
    }//GEN-LAST:event_tbSanPhamKeyPressed

    private void tbSanPhamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbSanPhamMouseClicked
        setForm();
    }//GEN-LAST:event_tbSanPhamMouseClicked

    private void cbLoaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbLoaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbLoaiActionPerformed
    public void setForm() {
        row = tbSanPham.getSelectedRow();
        tfID.setText(tbSanPham.getValueAt(row, 0).toString());
        tfName.setText(tbSanPham.getValueAt(row, 1).toString());
        loadLoai((LoaiThucPham) tbSanPham.getValueAt(row, 2), false);
        tfDonVi.setText(tbSanPham.getValueAt(row, 3).toString());
        tfSolo.setText(tbSanPham.getValueAt(row, 4).toString());
        spHanDung.setValue(tbSanPham.getValueAt(row, 5));
        tfSoluong.setText(tbSanPham.getValueAt(row, 6).toString());
        tfGiaBan.setText(tbSanPham.getValueAt(row, 7).toString());
    }
    public void loadLoai(LoaiThucPham loaiSelected, boolean isSearch) {
        cbLoai.setModel(new ComboBoxModelLoaiThucPham (loaiSelected, false));
    }
    public void resetForm() {
        row = -1;
        tfID.setText("");
        tfName.setText("");
        tfDonVi.setText("");
        tfSolo.setText("");
        tfGiaBan.setText("");
        tfSoluong.setText("");
    }

    private boolean isValid(String func, SanPham obj) {
        boolean result = true;
        switch (func) {
            case "add":
                if (obj.getNameSP().isEmpty()) {
                    JOptionPane.showMessageDialog(null, "Vui lòng nhập tên thực phẩm");
                    return false;
                }
                if (obj.getDonvi().isEmpty()) {
                    JOptionPane.showMessageDialog(null, "Vui lòng nhập đơn vị");
                    return false;
                }
                if (obj.getSolo().isEmpty()) {
                    JOptionPane.showMessageDialog(null, "Vui lòng nhập số lô");
                    return false;
                }
                if (obj.getSoluong().isEmpty()) {
                    JOptionPane.showMessageDialog(null, "Vui lòng nhập số lượng");
                    return false;
                } else {
                    try {
                        Integer.parseInt(tfSoluong.getText());
                    } catch (NumberFormatException e) {
                        JOptionPane.showMessageDialog(null, "Nhập số lượng là số");
                        return false;
                    }
                }
                if (obj.getDongia().isEmpty()) {
                    JOptionPane.showMessageDialog(null, "Vui lòng nhập giá bán");
                    return false;
                } else {
                    try {
                        Integer.parseInt(tfGiaBan.getText());
                    } catch (NumberFormatException e) {
                        JOptionPane.showMessageDialog(null, "Nhập giá bán là số");
                        return false;
                    }
                }
                break;
            case "del":
                if (obj.getIdSanPham() <= 0) {
                    JOptionPane.showMessageDialog(null, "Vui lòng chọn một dòng để xóa!");
                    result = false;
                }
                break;
            case "edit":
                if (obj.getIdSanPham() <= 0) {
                    JOptionPane.showMessageDialog(null, "Vui lòng chọn một dòng để sửa!");
                    return false;
                }
                if (obj.getNameSP().isEmpty()) {
                    JOptionPane.showMessageDialog(null, "Vui lòng nhập tên sản phẩm");
                    return false;
                }
                if (obj.getDonvi().isEmpty()) {
                    JOptionPane.showMessageDialog(null, "Vui lòng nhập đơn vị");
                    return false;
                }
                if (obj.getSolo().isEmpty()) {
                    JOptionPane.showMessageDialog(null, "Vui lòng nhập số lô");
                    return false;
                }
                if (obj.getSoluong().isEmpty()) {
                    JOptionPane.showMessageDialog(null, "Vui lòng nhập số lượng");
                    return false;
                } else {
                    try {
                        Integer.parseInt(tfSoluong.getText());
                    } catch (NumberFormatException e) {
                        JOptionPane.showMessageDialog(null, "Nhập số lượng là số");
                        return false;
                    }
                }
                if (obj.getDongia().isEmpty()) {
                    JOptionPane.showMessageDialog(null, "Vui lòng nhập giá bán");
                    return false;
                } else {
                    try {
                        Integer.parseInt(tfGiaBan.getText());
                    } catch (NumberFormatException e) {
                        JOptionPane.showMessageDialog(null, "Nhập giá bán là số");
                        return false;
                    }
                }
                break;
        }
        return result;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btNhapLai;
    private javax.swing.JButton btSua;
    private javax.swing.JButton btThem;
    private javax.swing.JButton btTimKiem;
    private javax.swing.JButton btXoa;
    private javax.swing.JComboBox cbLoai;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JPanel pnUserLeft;
    private javax.swing.JPanel pnUserRight;
    private javax.swing.JSpinner spHanDung;
    private javax.swing.JTable tbSanPham;
    private javax.swing.JTextField tfDonVi;
    private javax.swing.JTextField tfFind;
    private javax.swing.JTextField tfGiaBan;
    private javax.swing.JTextField tfID;
    private javax.swing.JTextField tfName;
    private javax.swing.JTextField tfSolo;
    private javax.swing.JTextField tfSoluong;
    // End of variables declaration//GEN-END:variables
}
